### ISSUE TITLE
Model Image Not Displaying

### ISSUE THREAD

**Issue by Dim5678** [chevyhu/Flysky-OpenTX-Test-Branch#6]
When a model image is selected from the model setup menu, the image doesn't display on either the main menu or the model select menu.

**Comment by arhifisyant** [comment]
yes. confirmed the image does not  appear yet. please make this happen.

**Comment by eshifri** [comment]
Actually, not only the image - the model name is also not displayed on the main screen.
This is rather big inconvenience.

**Comment by evildronepilot** [comment]
In my case...... After removing / changing home screen widget settings. Model image is gone and there is no way of bringing it back.

**Comment by genivos** [comment]
It seems that sometimes Layout2Pl.ModelBmp in the Model*.bin file sometimes is 'capped'. With a hex editor you can change that, however I had to fiddle with the widgets first before editing the .bin file to make the model name appear again.
This workaround was found by someone on RCgroups in the NV14 thread.
Someone else told:

_@Genvios, maybe you can report this on Github, the codepice causing this is: 
BaseWidgetFactory<ModelBitmapWidget> modelBitmapWidget("ModelBmp", NULL);
const WidgetFactory * defaultWidget = &modelBitmapWidget;

in the file: modelbmp.cpp._

and:

_I think it is a bug fix rather than a bug: the same code can be found in 2.2.2 and 2.2.3 versions.
Most likely, the bug was in the model creation code of the older NV14 FW._

Maybe this gives some clearance of what's going on.
